<!doctype html>
<html lang="en">

	<?php require_once("tempdb/DBconnect.php"); ?>

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Heatmap</title>
        <link rel="stylesheet" href="master.css" media="screen" title="core styles" charset="utf-8">
        <link rel="stylesheet" href="font-awesome/css/font-awesome.min.css">
    </head>
	
    <body>
	
        <div id="main-content-wrapper" class="container">

            <div id="marking-tool-panel">
                <button id="undo"><i class="fa fa-undo"></i></button>
            </div>

            <div id="heatmapCanvasContainer" oncontextmenu="return false;">
               <!-- heatmap canvas generated by js -->
            </div>

            <div id="heatmap-panel-container">
    			<ul id = "heatmapPanel">
    				<li>
                        <label>Hue</label><br>
                        <input id = "hueLevel" type="range" value = "0" min="0" max="360">
                        <span class = "sizeNumber">0</span>
                    </li>
    				<li>
                        <label>Saturation</label><br>
                        <input id = "satLevel" type="range" value = "50" min="0" max="100">
                        <span class = "sizeNumber">50</span>
                    </li>
    				<li>
                        <label>Hue scale (Multiple colors)</label><br>
                        <input type = "checkbox" id = "hueScale"><br>
                    </li>
                    <li>
                        <button type = "button" id = "genHeatmap">Generate heatmap</button>
                    </li>
    			</ul>
            </div>

        </div>


        <script src="jquery.js"></script>
        <script src="heatmap.js"></script>


    </body>
</html>
