<!doctype html>
<html lang="en">

	<?php require_once("tempdb/DBconnect.php"); ?>

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Heatmap</title>
        <link rel="stylesheet" href="css/master.css" media="screen" title="core styles" charset="utf-8">
        <link rel="stylesheet" href="css/heatmap.css" media="screen" title="core styles" charset="utf-8">
        <link rel="stylesheet" href="libs/font-awesome/css/font-awesome.min.css">
    </head>
	
    <body>
	
        <div id="main-content-wrapper" class="container">

            <div id="heatmapCanvasContainer" oncontextmenu="return false;">
               <!-- heatmap canvas generated by js -->
            </div>

            <div id="heatmap-panel-container">
    			<ul id = "heatmapPanel">
    				<li id = "hueSection">
                        <h2>hue</h2>
						<input type = "number" class = "sizeNumber" value = "0">
                        <div class = "rangeSlider">
							<div class = "rangeSliderLowValue">0</div> 
							<input id = "hueLevel" type="range" value = "0" min="0" max="360">
							<div class = "rangeSliderMaxValue">360</div>
                        <div>
                    </li>
    				<li id = "satSection">
                        <h2>saturation</h2>
						<input type = "number" class = "sizeNumber" value = "50">
						<div class = "rangeSlider">
							<div class = "rangeSliderLowValue">0</div> 
							<input id = "satLevel" type="range" value = "50" min="0" max="100">
							<div class = "rangeSliderMaxValue">100</div>
                        <div>
                    </li>
    				<li>
                        <input type = "checkbox" id = "hueScale">
						<label for = "hueScale">Hue scale (Multiple colors)</label>
                    </li>
					<li>
                        <input type = "checkbox" id = "reverseScale">
						<label for = "reverseScale">Reverse scale</label>
                    </li>
					<li>
                        <input type = "checkbox" id = "liveGen">
						<label for = "liveGen">Enable live generating (only for hardcore computers)</label>
                    </li>
                    <li>
                        <button type = "button" id = "genHeatmap">Generate heatmap</button>
						<a id = "downloadImage"><button type = "button" >Download image</button></a>
                    </li>
			
    			</ul>
            </div>

        </div>


        <script src="libs/jquery.js"></script>
        <script src="heatmap.js"></script>


    </body>
</html>
